---DSB ESB---
--[[ Autogenerated by ESB.
 Trying to edit this file by hand may not give you
 particularly good results.
]]

dsb_text2map(0, 10, 9, 100, 1, {
"1111100000",
"1111000000",
"1110110000",
"0001111100",
"1111001110",
"0001111100",
"0000110100",
"0000000100",
"0000010100"} )
dsb_level_wallset(0, wallset.default)
dsb_text2map(1, 21, 14, 0, 2, {
"000000000000000000000",
"000000000000000111100",
"011111110010000111000",
"001100000111011111111",
"000001101111110000000",
"000000100111011110000",
"000000110010000010000",
"000000110111011010000",
"000011110111111010000",
"000000110111011010000",
"000000010000000111000",
"000000011111000111000",
"000000001110000000000",
"000000000110000000000"} )
dsb_level_wallset(1, wallset.default)
dsb_alt_wallset(wallset.redfloor, 1, 16, 6, 4)
dsb_alt_wallset(wallset.redfloor, 1, 16, 7, 4)
dsb_alt_wallset(wallset.redfloor, 1, 16, 8, 4)
dsb_alt_wallset(wallset.redfloor, 1, 16, 9, 4)
dsb_add_champion(1, "TEST", "port_chani", "TEST", "PLAYER", 9000, 9000, 9000, 600, 500, 600, 500, 500, 500, 500, 6, 6, 6, 6)
dsb_add_champion(2, "TEST2", "port_daroou", "TEST2", "PLAYER", 9000, 9000, 9000, 700, 600, 500, 500, 500, 500, 500, 8, 6, 4, 4)
dsb_add_champion(3, "TEST3", "port_mophus", "TEST3", "PLAYER", 500, 600, 700, 400, 400, 600, 600, 500, 500, 500, 4, 5, 7, 7)
dsb_add_champion(4, "TEST4", "port_sonja", "TEST4", "PLAYER", 9000, 9000, 9000, 600, 600, 400, 400, 500, 500, 500, 6, 6, 6, 6)
ch_exvar = {
[1] = { useless_test_var = 1 },
}
dsb_spawnburst_begin(244)
dsb_spawn(2, "silk_shirt", CHARACTER, TEST, 3, 0)
dsb_spawn(3, "tabard", CHARACTER, TEST, 4, 0)
dsb_spawn(4, "boots_suede", CHARACTER, TEST, 5, 0)
dsb_spawn(5, "sword", CHARACTER, TEST, 0, 0)
dsb_spawn(6, "club", CHARACTER, TEST2, 13, 0)
dsb_spawn(7, "chest", CHARACTER, TEST2, 14, 0)
dsb_spawn(8, "drumstick", IN_OBJ, 7, 0, 0)
dsb_spawn(9, "drumstick", IN_OBJ, 7, 1, 0)
dsb_spawn(10, "drumstick", IN_OBJ, 7, 2, 0)
dsb_spawn(11, "drumstick", IN_OBJ, 7, 3, 0)
dsb_spawn(12, "drumstick", IN_OBJ, 7, 4, 0)
dsb_spawn(13, "drumstick", IN_OBJ, 7, 5, 0)
dsb_spawn(14, "drumstick", IN_OBJ, 7, 6, 0)
dsb_spawn(15, "drumstick", IN_OBJ, 7, 7, 0)
dsb_spawn(16, "robe_fine_top", CHARACTER, TEST3, 3, 0)
dsb_spawn(17, "robe_fine_bottom", CHARACTER, TEST3, 4, 0)
dsb_spawn(18, "sandals", CHARACTER, TEST3, 5, 0)
dsb_spawn(19, "wand", CHARACTER, TEST3, 13, 0)
dsb_set_charge(19, 15)
dsb_spawn(20, "halter", CHARACTER, TEST4, 3, 0)
dsb_spawn(21, "tattered_pants", CHARACTER, TEST4, 4, 0)
dsb_spawn(22, "boots_leather", CHARACTER, TEST4, 5, 0)
dsb_spawn(39, "sconce_full", 0, 4, 1, 2)
dsb_spawn(40, "torch", IN_OBJ, 39, 0, 0)
dsb_set_charge(40, 244)
dsb_spawn(29, "alcove_short_bottom", 0, 5, 1, 2)
dsb_spawn(33, "waterskin_full", IN_OBJ, 29, 0, 0)
dsb_spawn(30, "alcove_short_top", 0, 5, 1, 2)
dsb_spawn(34, "dagger", IN_OBJ, 30, 0, 0)
dsb_spawn(244, "ghost", 0, 2, 2, 1)
dsb_spawn(23, "apple", 0, 4, 2, 0)
dsb_spawn(26, "flask", 0, 5, 2, 1)
dsb_spawn(44, "alcove_short_top", 0, 6, 2, 2)
dsb_spawn(180, "falchion", IN_OBJ, 44, 0, 0)
dsb_spawn(45, "alcove_short_bottom", 0, 6, 2, 2)
dsb_disable(45)
dsb_spawn(181, "mace", IN_OBJ, 45, 0, 0)
dsb_spawn(48, "button_blue", 0, 7, 2, 2)
dsb_spawn(242, "alcove_vi", 0, 8, 3, 3)
dsb_spawn(27, "doorframe", 0, 0, 4, 4)
dsb_spawn(28, "door_black", 0, 0, 4, 4)
dsb_spawn(159, "floortext", 0, 2, 4, 4)
dsb_spawn(1, "wallwriting", 0, 4, 4, 3)
dsb_spawn(41, "mirror", 0, 5, 4, 0)
dsb_spawn(42, "mirror", 0, 5, 4, 1)
dsb_spawn(43, "mirror", 0, 5, 4, 2)
dsb_spawn(51, "stairsdown", 0, 8, 4, 4)
dsb_spawn(53, "alcove", 0, 8, 5, 3)
dsb_spawn(55, "dart_poison", 0, 8, 5, 3)
dsb_spawn(56, "dart_poison", 0, 8, 5, 3)
dsb_spawn(57, "dart_poison", 0, 8, 5, 3)
dsb_spawn(58, "dart_poison", 0, 8, 5, 3)
dsb_spawn(59, "dart_poison", 0, 8, 5, 3)
dsb_spawn(54, "scroll", 0, 8, 5, 3)
dsb_spawn(24, "apple", 0, 4, 6, 3)
dsb_spawn(25, "flask", 0, 5, 6, 2)
dsb_spawn(46, "alcove_short_top", 0, 6, 6, 0)
dsb_spawn(49, "scroll", IN_OBJ, 46, 0, 0)
dsb_spawn(47, "alcove_short_bottom", 0, 6, 6, 0)
dsb_spawn(50, "skillscroll", IN_OBJ, 47, 0, 0)
dsb_spawn(238, "wallwriting", 0, 6, 6, 1)
dsb_spawn(243, "button_blue", 0, 6, 6, 3)
dsb_spawn(236, "pad", 0, 7, 6, 4)
dsb_spawn(237, "trigger_controller", 0, 8, 6, 4)
dsb_spawn(37, "sconce_full", 0, 4, 7, 0)
dsb_spawn(38, "torch", IN_OBJ, 37, 0, 0)
dsb_set_charge(38, 244)
dsb_spawn(31, "alcove_short_bottom", 0, 5, 7, 0)
dsb_spawn(35, "illumulet", IN_OBJ, 31, 0, 0)
dsb_spawn(32, "alcove_short_top", 0, 5, 7, 0)
dsb_spawn(36, "item_action", 0, 6, 7, 4)
dsb_spawn(217, "doorframe", 0, 7, 7, 4)
dsb_spawn(235, "door_wood", 0, 7, 7, 4)
dsb_spawn(239, "hellhound", 0, 7, 8, 4)
dsb_spawn(204, "msg_sender", 1, 14, 0, 4)
dsb_spawn(203, "sequencer", 1, 15, 0, 4)
dsb_spawn(151, "hook", 1, 16, 0, 2)
dsb_spawn(154, "slimedrain", 1, 17, 0, 2)
dsb_spawn(229, "alcove", 1, 2, 1, 2)
dsb_spawn(230, "firestaff", 1, 2, 1, 2)
dsb_spawn(169, "ring_plain", 1, 5, 1, 2)
dsb_spawn(79, "eye", 1, 10, 1, 2)
dsb_spawn(195, "bluehaze", 1, 15, 1, 4)
dsb_disable(195)
dsb_spawn(196, "bluehaze", 1, 16, 1, 4)
dsb_disable(196)
dsb_spawn(197, "bluehaze", 1, 17, 1, 4)
dsb_disable(197)
dsb_spawn(144, "monster_generator", 1, 18, 1, 4)
dsb_spawn(231, "amalgam", 1, 0, 2, 1)
dsb_spawn(232, "amalgam_gembare", 1, 0, 2, 1)
dsb_disable(232)
dsb_spawn(233, "amalgam_empty", 1, 0, 2, 1)
dsb_disable(233)
dsb_spawn(223, "function_caller", 1, 1, 2, 4)
dsb_spawn(167, "pad", 1, 6, 2, 4)
dsb_spawn(160, "teleporter", 1, 7, 2, 4)
dsb_spawn(161, "bluehaze", 1, 7, 2, 4)
dsb_spawn(78, "wallwriting", 1, 9, 2, 1)
dsb_spawn(80, "qswapper", 1, 11, 2, 4)
dsb_spawn(85, "sequencer", 1, 13, 2, 4)
dsb_spawn(202, "bluehaze", 1, 15, 2, 4)
dsb_disable(202)
dsb_spawn(149, "monster_capturer", 1, 16, 2, 0)
dsb_spawn(150, "squaredrain", 1, 16, 2, 4)
dsb_spawn(198, "bluehaze", 1, 17, 2, 4)
dsb_disable(198)
dsb_spawn(145, "button_redcross", 1, 18, 2, 3)
dsb_spawn(234, "qswapper", 1, 0, 3, 4)
dsb_spawn(221, "alcove_vi", 1, 1, 3, 1)
dsb_spawn(224, "trigger", 1, 1, 3, 4)
dsb_spawn(225, "s_slice", 1, 3, 3, 2)
dsb_spawn(226, "drumstick", 1, 3, 3, 2)
dsb_spawn(227, "worm_round", 1, 3, 3, 2)
dsb_spawn(170, "gorface", 1, 5, 3, 0)
dsb_spawn(171, "gorface", 1, 5, 3, 2)
dsb_spawn(162, "movablewall", 1, 5, 3, 4)
dsb_spawn(228, "monster_blocker", 1, 5, 3, 4)
dsb_spawn(163, "button_blue", 1, 6, 3, 2)
dsb_spawn(168, "qswapper", 1, 7, 3, 4)
dsb_spawn(76, "fountain_medusa", 1, 8, 3, 1)
dsb_spawn(74, "fountain_medusa", 1, 12, 3, 3)
dsb_spawn(81, "doorframe", 1, 14, 3, 4)
dsb_spawn(82, "door_metal_redlock", 1, 14, 3, 4)
dsb_spawn(201, "bluehaze", 1, 15, 3, 4)
dsb_disable(201)
dsb_spawn(200, "bluehaze", 1, 16, 3, 4)
dsb_disable(200)
dsb_spawn(199, "bluehaze", 1, 17, 3, 4)
dsb_disable(199)
dsb_spawn(146, "doorframe", 1, 18, 3, 4)
dsb_spawn(147, "door_portcullis_bottomlock", 1, 18, 3, 4)
dsb_set_crop(147, 16)
dsb_spawn(148, "psychic_demon", 1, 19, 3, 4)
dsb_set_facedir(148, 3)
dsb_spawn(222, "wallwriting", 1, 2, 4, 0)
dsb_spawn(164, "button_blue", 1, 4, 4, 1)
dsb_spawn(165, "button_blue", 1, 7, 4, 3)
dsb_spawn(52, "stairsup", 1, 8, 4, 4)
dsb_spawn(73, "crazy_axe", 1, 10, 4, 0)
dsb_spawn(102, "arrow", 1, 10, 4, 1)
dsb_spawn(103, "arrow", 1, 10, 4, 1)
dsb_spawn(104, "arrow", 1, 10, 4, 1)
dsb_spawn(105, "arrow", 1, 10, 4, 1)
dsb_spawn(106, "arrow", 1, 10, 4, 1)
dsb_spawn(107, "arrow", 1, 10, 4, 1)
dsb_spawn(108, "arrow", 1, 10, 4, 1)
dsb_spawn(109, "arrow", 1, 10, 4, 1)
dsb_spawn(100, "quiver", 1, 10, 4, 2)
dsb_spawn(101, "bow", 1, 10, 4, 3)
dsb_spawn(240, "dm2table", 1, 10, 4, 4)
dsb_spawn(137, "monster_blocker", 1, 12, 4, 4)
dsb_spawn(87, "scroll", 1, 13, 4, 1)
dsb_spawn(205, "trigger", 1, 13, 4, 4)
dsb_spawn(86, "button_green", 1, 14, 4, 3)
dsb_spawn(152, "manacles", 1, 16, 4, 0)
dsb_spawn(153, "ring_plain", 1, 17, 4, 0)
dsb_spawn(166, "counter", 1, 5, 5, 4)
dsb_spawn(134, "doorframe", 1, 6, 5, 4)
dsb_spawn(135, "door_wood_ornate", 1, 6, 5, 4)
dsb_spawn(136, "alcove", 1, 7, 5, 2)
dsb_spawn(155, "trigger_apple", 1, 7, 5, 2)
dsb_spawn(156, "scroll", 1, 7, 5, 2)
dsb_spawn(77, "fountain_medusa", 1, 8, 5, 1)
dsb_spawn(75, "fountain_medusa", 1, 12, 5, 3)
dsb_spawn(83, "doorframe", 1, 14, 5, 4)
dsb_spawn(84, "door_metal_redlock", 1, 14, 5, 4)
dsb_spawn(116, "trigger", 1, 16, 5, 4)
dsb_spawn(110, "wallwriting", 1, 17, 5, 3)
dsb_spawn(186, "rusting_ruster", 1, 7, 6, 4)
dsb_set_facedir(186, 2)
dsb_spawn(60, "doorframe", 1, 10, 6, 4)
dsb_spawn(61, "door_portcullis", 1, 10, 6, 4)
dsb_spawn(62, "doorbutton", 1, 10, 6, 4)
dsb_spawn(173, "item_action", 1, 12, 6, 4)
dsb_spawn(133, "alcove2", 1, 13, 6, 2)
dsb_spawn(172, "scroll", 1, 13, 6, 2)
dsb_spawn(111, "floordamager", 1, 16, 6, 4)
dsb_disable(111)
dsb_spawn(115, "msg_sender", 1, 17, 6, 4)
dsb_spawn(65, "throwtrolin", 1, 10, 7, 0)
dsb_spawn(66, "throwtrolin", 1, 10, 7, 1)
dsb_spawn(68, "throwtrolin", 1, 10, 7, 2)
dsb_spawn(67, "throwtrolin", 1, 10, 7, 3)
dsb_spawn(64, "floorslime", 1, 11, 7, 4)
dsb_spawn(157, "coinslot", 1, 12, 7, 1)
dsb_spawn(112, "floordamager", 1, 16, 7, 4)
dsb_disable(112)
dsb_spawn(210, "giggler", 1, 4, 8, 4)
mon_hp(210, 50)
dsb_set_facedir(210, 1)
dsb_spawn(174, "doorframe", 1, 5, 8, 4)
dsb_spawn(207, "door_metal", 1, 5, 8, 4)
dsb_spawn(138, "rusting_ruster", 1, 6, 8, 4)
dsb_set_facedir(138, 2)
dsb_spawn(139, "rusting_ruster", 1, 7, 8, 4)
dsb_set_facedir(139, 2)
dsb_spawn(206, "button_blue", 1, 8, 8, 1)
dsb_spawn(70, "throwtrolin", 1, 9, 8, 0)
dsb_spawn(71, "throwtrolin", 1, 9, 8, 1)
dsb_spawn(72, "throwtrolin", 1, 9, 8, 2)
dsb_spawn(69, "throwtrolin", 1, 9, 8, 3)
dsb_spawn(63, "floorslime", 1, 10, 8, 4)
dsb_spawn(89, "doorframe", 1, 12, 8, 4)
dsb_spawn(90, "door_black", 1, 12, 8, 4)
dsb_spawn(93, "alcove2", 1, 15, 8, 3)
dsb_spawn(94, "moneybox", 1, 15, 8, 3)
dsb_spawn(95, "coin_copper", IN_OBJ, 94, 0, 0)
dsb_spawn(96, "coin_gold", IN_OBJ, 94, 1, 0)
dsb_spawn(97, "coin_gold", IN_OBJ, 94, 2, 0)
dsb_spawn(98, "coin_gold", IN_OBJ, 94, 3, 0)
dsb_spawn(99, "gem_orange", IN_OBJ, 94, 4, 0)
dsb_spawn(113, "floordamager", 1, 16, 8, 4)
dsb_disable(113)
dsb_spawn(211, "ambient_sound", 1, 4, 9, 4)
dsb_spawn(208, "alcove", 1, 5, 9, 1)
dsb_spawn(212, "pad", 1, 5, 9, 4)
dsb_spawn(215, "coin_copper", 1, 6, 9, 3)
dsb_spawn(216, "coin_copper", 1, 6, 9, 3)
dsb_spawn(122, "coin_copper", 1, 9, 9, 2)
dsb_spawn(131, "coin_gold", 1, 9, 9, 3)
dsb_spawn(132, "coin_silver", 1, 9, 9, 3)
dsb_spawn(91, "keyhole_gold", 1, 12, 9, 3)
dsb_spawn(92, "multivexirk", 1, 14, 9, 4)
dsb_set_facedir(92, 3)
dsb_spawn(193, "slayer", IN_OBJ, 92, 0, 0)
dsb_spawn(194, "slayer", IN_OBJ, 92, 1, 0)
dsb_spawn(114, "floordamager", 1, 16, 9, 4)
dsb_disable(114)
dsb_spawn(241, "monster_blocker", 1, 16, 9, 4)
dsb_spawn(214, "counter", 1, 4, 10, 4)
dsb_spawn(213, "item_action", 1, 5, 10, 4)
dsb_spawn(209, "wallwriting", 1, 6, 10, 0)
dsb_spawn(123, "doorframe", 1, 7, 10, 4)
dsb_spawn(124, "door_metal", 1, 7, 10, 4)
dsb_spawn(120, "gemhole", 1, 10, 10, 0)
dsb_spawn(119, "movablewall", 1, 10, 10, 4)
dsb_spawn(121, "ambient_sound", 1, 10, 10, 4)
dsb_spawn(175, "alcove2", 1, 13, 10, 0)
dsb_spawn(176, "footplate", 1, 13, 10, 0)
dsb_spawn(177, "legplate", 1, 13, 10, 0)
dsb_spawn(178, "torsoplate", 1, 13, 10, 0)
dsb_spawn(179, "armet", 1, 13, 10, 0)
dsb_spawn(140, "fountain_lion", 1, 14, 10, 1)
dsb_spawn(143, "flask", 1, 15, 10, 0)
dsb_spawn(88, "key_gold", 1, 15, 10, 0)
dsb_spawn(142, "gem_orange", 1, 17, 10, 1)
dsb_spawn(141, "fountain_lion", 1, 18, 10, 3)
dsb_spawn(125, "scroll", 1, 7, 11, 0)
dsb_spawn(158, "floorcrack", 1, 9, 11, 4)
dsb_spawn(126, "s_slice", 1, 11, 11, 1)
dsb_spawn(128, "worm_round", 1, 11, 11, 1)
dsb_spawn(129, "d_steak", 1, 11, 11, 1)
dsb_spawn(130, "eye_of_time", 1, 11, 11, 1)
dsb_set_charge(130, 5)
dsb_spawn(127, "fakewall", 1, 11, 11, 4)
dsb_spawn(118, "scroll", 1, 16, 11, 2)
dsb_spawn(187, "worm", 1, 8, 12, 1)
dsb_set_facedir(187, 1)
dsb_spawn(188, "worm2y", 1, 8, 12, 2)
dsb_set_facedir(188, 1)
dsb_spawn(189, "muncher", 1, 10, 12, 0)
dsb_spawn(191, "wasp", 1, 10, 12, 1)
dsb_spawn(190, "muncher", 1, 10, 12, 2)
dsb_spawn(192, "wasp", 1, 10, 12, 3)
dsb_spawn(117, "gorface", 1, 16, 12, 0)
dsb_spawn(220, "item_action", 1, 7, 13, 4)
dsb_spawn(218, "wallwriting", 1, 8, 13, 1)
dsb_spawn(219, "button_blue", 1, 8, 13, 1)
dsb_spawn(185, "shield_lyte", 1, 10, 13, 2)
dsb_spawn(184, "shield_large", 1, 10, 13, 2)
dsb_spawn(183, "shield_wood", 1, 10, 13, 2)
dsb_spawn(182, "shield_buckler", 1, 10, 13, 2)
exvar = {
[1] = { text = "WELCOME TO DSB/ENJOY YOUR STAY/BUT BEWARE OF/MONSTERS" },
[36] = { target_mode = 3,
target = 32,
move_mode = 2,
target_arch = "dexhelm" },
[37] = { release = true },
[39] = { release = true },
[41] = { champion = 2 },
[42] = { champion = 3 },
[43] = { champion = 4 },
[48] = { target = { 44, 45 },
msg = 100002 },
[49] = { text = "FIREBALL/FUL KATH//CREATE WATER/VI BRO NETA//MAGIC BOMB/FUL GOR" },
[50] = { text = "EDIT ME" },
[54] = { text = "THESE/POISON DARTS/WILL DAMAGE/MONSTERS/OVER TIME" },
[62] = { target = 61 },
[78] = { text = "WATER/PURIFICATION" },
[79] = { target = 80,
opby = "flask_water_yucky",
msg = 100000 },
[80] = { arch = "flask_water",
target_opby = true },
[85] = { target = { 82, 82, 84, 84 },
msg = { 100001, 100000, 100001, 100000 } },
[86] = { target = 85,
msg = 100000 },
[87] = { text = "CHOOSE/YOUR/PATH" },
[91] = { destroy = true,
opby = "key_gold",
disable_self = true,
msg = 100001,
target = 90 },
[110] = { text = "CORRIDOR/OF PAIN" },
[111] = { dmg_type = 0,
dmg_amt = 5 },
[112] = { dmg_type = 0,
dmg_amt = 5 },
[113] = { dmg_type = 0,
dmg_amt = 5 },
[114] = { dmg_type = 0,
dmg_amt = 5 },
[115] = { target = { 111, 111, 112, 112, 113, 113, 114, 114 },
msg = 100002,
repeat_rate = 2 },
[116] = { target = 115,
opby_party = true,
disable_self = true,
msg = 100000 },
[117] = { silent = true,
func = "dragon_show" },
[118] = { text = "TOUCH THE FACE/OF GOR/TO BEHOLD/THE MIGHTY/DRAGON" },
[120] = { destroy = true,
opby = "gem_orange",
target = { 121, 119 },
msg = { 100000, 100001 },
delay = { 2, 3 },
disable_self = true },
[121] = { sound = "explosion",
no_loop = true },
[124] = { bash_power = 1,
fire_power = 1 },
[125] = { text = "WEAKER THAN/IT LOOKS" },
[144] = { min = 1,
generates = "screamer",
max = 4,
sound = "zap",
regen = 10 },
[145] = { target = { 144, 147 },
msg = { 100000, 100002 } },
[155] = { target = 135,
msg = 100001 },
[156] = { text = "EAT THE APPLE/TO OPEN/THE DOOR" },
[157] = { destroy = true,
opby = "coin_gold",
target = 173,
msg = 100000 },
[159] = { disable_self = true,
text = "WELCOME TO THE TEST DUNGEON/FEEL FREE TO LOOK AROUND",
color = { 255, 0, 160 } },
[160] = { y = 4,
x = 6,
opby_party = true,
opby_thing = true,
opby_monster = true,
not_in_air = true,
spin = 2 },
[163] = { target = 166,
msg = 100000,
disable_self = true },
[164] = { target = 166,
msg = 100000,
disable_self = true },
[165] = { target = 166,
msg = 100000,
disable_self = true },
[166] = { target = 162,
msg = 100001,
count = 3 },
[167] = { target = { 163, 164, 165, 166, 168 },
opby_party = true,
msg = { 100005, 100005, 100005, 100005, 100000 } },
[168] = { target = { 163, 164, 165 },
arch = "button_blue" },
[172] = { text = "SWORDS/FOR SALE//ONE GOLD COIN" },
[173] = { target_arch = "sword",
move_mode = 1,
move_lev = 1,
move_x = 13,
move_face = 2,
target_mode = 3,
move_y = 6 },
[203] = { target = { 195, 196, 197, 198, 199, 200, 201, 202 },
msg = 100000,
send_reverse = true },
[204] = { target = 203,
msg = 100000,
repeat_rate = 4 },
[205] = { target = 204,
opby_party = true,
msg = 100000,
disable_self = true },
[206] = { func = "leader_mystery" },
[209] = { text = "PLACE/BRIBES/IN THE/ALCOVE" },
[211] = { sound = "monster_oowooah",
no_loop = true },
[212] = { target = { 213, 214, 211 },
msg = 100000,
opby_thing = true },
[213] = { target = 210,
move_mode = 2,
target_mode = 1 },
[214] = { target = { 207, 212 },
msg = 100001,
count = 2 },
[218] = { text = "//ARROW/GATHERER" },
[219] = { target = 220,
msg = 100000 },
[220] = { target_mode = 4,
move_mode = 4,
target_arch = "arrow",
inv_char = -1,
inv_put_away = true },
[222] = { text = "MONSTER/REVIVER" },
[223] = { m_a = "monster_reviver" },
[224] = { target = 223,
no_tc = true,
opby_thing = true,
msg = 100000 },
[231] = { destroy = true,
opby = "zokathra",
target = { 231, 232 },
msg = { 100001, 100000 },
sound = "zap" },
[232] = { target = { 234, 232, 233 },
opby = "firestaff",
sound = "explosion",
msg = { 100000, 100001, 100000 } },
[234] = { target_opby = true,
full_swap = true,
arch = "firestaff_gem" },
[235] = { bash_power = 9999,
fire_power = 9999 },
[236] = { target = 237,
opby_party = true,
msg = 100000 },
[237] = { party_members = 2,
msg = 100001,
party_contains = 0,
target = 235 },
[238] = { text = "AT LEAST/TWO PEOPLE/MUST STAND/HERE" },
[243] = { target = 36,
msg = 100000,
disable_self = true },
}
dsb_spawnburst_end()
EDITOR_FLAGS = 255
dsb_champion_toparty(0, 1)
dsb_party_place(0, 1, 4, 1)

